# Generated by Django 6.0.5 on 2026-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
