# Generated by Django 6.0.5 on 2026-06-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='linl',
            new_name='link',
        ),
    ]
